### ISSUE TITLE
Error when executing training

### ISSUE THREAD

**Issue by khakimin** [jinfagang/yolov7#129]
Hello, I have this error issue when I execute training using r50.yaml: 

Starting training from iteration 0
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:593: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2981.)
  lbox = tgt_scale * lbox.T
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
/content/yolov7/yolov7/modeling/meta_arch/yolov7.py:704: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  best_n_mask = (best_n_all // 3) == self.level
ERROR [07/26 06:52:27 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/content/yolov7/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/content/yolov7/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/content/yolov7/detectron2/detectron2/engine/train_loop.py", line 274, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 344, in forward
    for out, loss_evaluator in zip(outs, self.loss_evaluators)
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 344, in <listcomp>
    for out, loss_evaluator in zip(outs, self.loss_evaluators)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 536, in forward
    self.ignore_threshold,
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 748, in get_target
    tcls[b, a, gj, gi, int(target[b, t, 0])] = 1
IndexError: index 2 is out of bounds for dimension 4 with size 2
[07/26 06:52:27 d2.engine.hooks]: Overall training speed: 6 iterations in 0:00:01 (0.1800 s / it)
[07/26 06:52:27 d2.engine.hooks]: Total training time: 0:00:01 (0:00:00 on hooks)
[07/26 06:52:27 d2.utils.events]:  eta: 0:11:11  iter: 8  total_loss: 2.15e+04  loss_iou: 0.7954  loss_xy: 2.045  loss_wh: 2.965  loss_conf: 2.149e+04  loss_cls: 2.107  time: 0.1662  data_time: 0.0225  lr: 1.2478e-08  max_mem: 1173M
Traceback (most recent call last):
  File "train_PVdefectv7icoco.py", line 84, in <module>
    args=(args,),
  File "/content/yolov7/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_PVdefectv7icoco.py", line 73, in main
    return trainer.train()
  File "/content/yolov7/detectron2/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/content/yolov7/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/content/yolov7/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/content/yolov7/detectron2/detectron2/engine/train_loop.py", line 274, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 344, in forward
    for out, loss_evaluator in zip(outs, self.loss_evaluators)
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 344, in <listcomp>
    for out, loss_evaluator in zip(outs, self.loss_evaluators)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 536, in forward
    self.ignore_threshold,
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 748, in get_target
    tcls[b, a, gj, gi, int(target[b, t, 0])] = 1
IndexError: index 2 is out of bounds for dimension 4 with size 2

Can anyone help show the right way please?

**Comment by jinfagang** [comment]
using yolox, yolov7 arch is deprecated.
