### ISSUE TITLE
Problems Exporting-AttributeError: YOLOF

### ISSUE THREAD

**Issue by frankvp11** [jinfagang/yolov7#159]
Traceback:
/content/yolov7
Install mish-cuda to speed up training and inference. More importantly, replace the naive Mish with MishCuda will give a ~1.5G memory saving during training.
[08/09 17:06:50 detectron2]: Arguments: Namespace(confidence_threshold=0.65, config_file='/content/yolov7/configs/Base-YOLOF.yaml', input='./images/COCO_val2014_000000001722.jpg', opts=[], output=None, verbose=True, video_input=None, webcam=False)
WARNING [08/09 17:06:50 d2.config.compat]: Config '/content/yolov7/configs/Base-YOLOF.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "export.py", line 265, in <module>
    predictor = DefaultPredictor(cfg)
  File "export.py", line 47, in __init__
    self.model = build_model(self.cfg)
  File "/usr/local/lib/python3.7/dist-packages/detectron2-0.6-py3.7-linux-x86_64.egg/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/usr/local/lib/python3.7/dist-packages/detectron2-0.6-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2-0.6-py3.7-linux-x86_64.egg/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/content/yolov7/yolov7/modeling/meta_arch/yolof.py", line 171, in from_config
    backbone_level = cfg.MODEL.YOLOF.ENCODER.BACKBONE_LEVEL
  File "/usr/local/lib/python3.7/dist-packages/yacs-0.1.8-py3.7.egg/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: YOLOF

Command:
%cd /content/yolov7
!python3 export.py --config-file /content/yolov7/configs/Base-YOLOF.yaml  -v

**Comment by frankvp11** [comment]
Why did you close it? It wasn't fixed? @jinfagang
