### ISSUE TITLE
Anchordetr exportation to onnx 

### ISSUE THREAD

**Issue by mareking1412** [jinfagang/yolov7#22]
Thank you so much for your work @jinfagang. I have tested to export detr to onnx, and failed,  I used AnchorDETR_r50_c5 as anchordetr_origin, my torch version is 1.8.0, and my onnx version is 1.11.0, could you tell me how can i get a right  model? thank you very much!

Traceback (most recent call last):
  File "export_onnx.py", line 262, in <module>
    torch.onnx.export(model, inp, onnx_f, output_names={
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 691, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 454, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args,
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 417, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 377, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/jit/_trace.py", line 1139, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/jit/_trace.py", line 125, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/xj/yolov7-main/yolov7/modeling/meta_arch/anchor_detr.py", line 183, in forward
    self.detr.backbone.prepare_onnx_export()
  File "/home/xj/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MaskedBackboneTraceFriendly' object has no attribute 'prepare_onnx_export'

**Comment by jinfagang** [comment]
@mareking1412 AnchorDETR not fully support to export onnx, you may try detr first, and then modification accordingly to support AnchorDETR.
PR are very welcome.
