### ISSUE TITLE
demo.py detect will create an error

### ISSUE THREAD

**Issue by CaffeMrDe** [jinfagang/yolov7#23]
`
xxx:~/work/yolov7$ python3 demo.py --config-file configs/coco/sparseinst/sparse_inst_r50vd_giam_aug.yaml --input /home/jsj/work/yolov7/images/2.jpg --opts MODEL.WEIGHTS weights/sparse.pth 
Install mish-cuda to speed up training and inference. More importantly, replace the naive Mish with MishCuda will give a ~1.5G memory saving during training.
[04/26 21:55:23 detectron2]: Arguments: Namespace(confidence_threshold=0.21, config_file='configs/coco/sparseinst/sparse_inst_r50vd_giam_aug.yaml', input='/home/jsj/work/yolov7/images/2.jpg', nms_threshold=0.6, opts=['MODEL.WEIGHTS', 'weights/sparse.pth'], output=None, video_input=None, webcam=False)
[04/26 21:55:26 fvcore.common.checkpoint]: [Checkpointer] Loading from weights/sparse.pth ...
WARNING [04/26 21:55:26 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
backbone.bn1.{bias, weight}
backbone.conv1.0.weight
backbone.conv1.1.{bias, weight}
backbone.conv1.3.weight
backbone.conv1.4.{bias, weight}
backbone.conv1.6.weight
backbone.layer1.0.bn1.{bias, weight}
backbone.layer1.0.bn2.{bias, weight}
backbone.layer1.0.bn3.{bias, weight}
backbone.layer1.0.conv1.weight
backbone.layer1.0.conv2.weight
backbone.layer1.0.conv3.weight
backbone.layer1.0.downsample.1.weight
backbone.layer1.0.downsample.2.{bias, weight}
backbone.layer1.1.bn1.{bias, weight}
backbone.layer1.1.bn2.{bias, weight}
backbone.layer1.1.bn3.{bias, weight}
backbone.layer1.1.conv1.weight
backbone.layer1.1.conv2.weight
backbone.layer1.1.conv3.weight
backbone.layer1.2.bn1.{bias, weight}
backbone.layer1.2.bn2.{bias, weight}
backbone.layer1.2.bn3.{bias, weight}
backbone.layer1.2.conv1.weight
backbone.layer1.2.conv2.weight
backbone.layer1.2.conv3.weight
backbone.layer2.0.bn1.{bias, weight}
backbone.layer2.0.bn2.{bias, weight}
backbone.layer2.0.bn3.{bias, weight}
backbone.layer2.0.conv1.weight
backbone.layer2.0.conv2.weight
backbone.layer2.0.conv3.weight
backbone.layer2.0.downsample.1.weight
backbone.layer2.0.downsample.2.{bias, weight}
backbone.layer2.1.bn1.{bias, weight}
backbone.layer2.1.bn2.{bias, weight}
backbone.layer2.1.bn3.{bias, weight}
backbone.layer2.1.conv1.weight
backbone.layer2.1.conv2.weight
backbone.layer2.1.conv3.weight
backbone.layer2.2.bn1.{bias, weight}
backbone.layer2.2.bn2.{bias, weight}
backbone.layer2.2.bn3.{bias, weight}
backbone.layer2.2.conv1.weight
backbone.layer2.2.conv2.weight
backbone.layer2.2.conv3.weight
backbone.layer2.3.bn1.{bias, weight}
backbone.layer2.3.bn2.{bias, weight}
backbone.layer2.3.bn3.{bias, weight}
backbone.layer2.3.conv1.weight
backbone.layer2.3.conv2.weight
backbone.layer2.3.conv3.weight
backbone.layer3.0.bn1.{bias, weight}
backbone.layer3.0.bn2.{bias, weight}
backbone.layer3.0.bn3.{bias, weight}
backbone.layer3.0.conv1.weight
backbone.layer3.0.conv2.weight
backbone.layer3.0.conv3.weight
backbone.layer3.0.downsample.1.weight
backbone.layer3.0.downsample.2.{bias, weight}
backbone.layer3.1.bn1.{bias, weight}
backbone.layer3.1.bn2.{bias, weight}
backbone.layer3.1.bn3.{bias, weight}
backbone.layer3.1.conv1.weight
backbone.layer3.1.conv2.weight
backbone.layer3.1.conv3.weight
backbone.layer3.2.bn1.{bias, weight}
backbone.layer3.2.bn2.{bias, weight}
backbone.layer3.2.bn3.{bias, weight}
backbone.layer3.2.conv1.weight
backbone.layer3.2.conv2.weight
backbone.layer3.2.conv3.weight
backbone.layer3.3.bn1.{bias, weight}
backbone.layer3.3.bn2.{bias, weight}
backbone.layer3.3.bn3.{bias, weight}
backbone.layer3.3.conv1.weight
backbone.layer3.3.conv2.weight
backbone.layer3.3.conv3.weight
backbone.layer3.4.bn1.{bias, weight}
backbone.layer3.4.bn2.{bias, weight}
backbone.layer3.4.bn3.{bias, weight}
backbone.layer3.4.conv1.weight
backbone.layer3.4.conv2.weight
backbone.layer3.4.conv3.weight
backbone.layer3.5.bn1.{bias, weight}
backbone.layer3.5.bn2.{bias, weight}
backbone.layer3.5.bn3.{bias, weight}
backbone.layer3.5.conv1.weight
backbone.layer3.5.conv2.weight
backbone.layer3.5.conv3.weight
backbone.layer4.0.bn1.{bias, weight}
backbone.layer4.0.bn2.{bias, weight}
backbone.layer4.0.bn3.{bias, weight}
backbone.layer4.0.conv1.weight
backbone.layer4.0.conv2.weight
backbone.layer4.0.conv3.weight
backbone.layer4.0.downsample.1.weight
backbone.layer4.0.downsample.2.{bias, weight}
backbone.layer4.1.bn1.{bias, weight}
backbone.layer4.1.bn2.{bias, weight}
backbone.layer4.1.bn3.{bias, weight}
backbone.layer4.1.conv1.weight
backbone.layer4.1.conv2.weight
backbone.layer4.1.conv3.weight
backbone.layer4.2.bn1.{bias, weight}
backbone.layer4.2.bn2.{bias, weight}
backbone.layer4.2.bn3.{bias, weight}
backbone.layer4.2.conv1.weight
backbone.layer4.2.conv2.weight
backbone.layer4.2.conv3.weight
WARNING [04/26 21:55:26 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  backbone.stem.conv1.weight
  backbone.stem.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res2.0.shortcut.weight
  backbone.res2.0.shortcut.norm.{bias, running_mean, running_var, weight}
  backbone.res2.0.conv1.weight
  backbone.res2.0.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res2.0.conv2.weight
  backbone.res2.0.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res2.0.conv3.weight
  backbone.res2.0.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res2.1.conv1.weight
  backbone.res2.1.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res2.1.conv2.weight
  backbone.res2.1.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res2.1.conv3.weight
  backbone.res2.1.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res2.2.conv1.weight
  backbone.res2.2.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res2.2.conv2.weight
  backbone.res2.2.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res2.2.conv3.weight
  backbone.res2.2.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res3.0.shortcut.weight
  backbone.res3.0.shortcut.norm.{bias, running_mean, running_var, weight}
  backbone.res3.0.conv1.weight
  backbone.res3.0.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res3.0.conv2.weight
  backbone.res3.0.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res3.0.conv3.weight
  backbone.res3.0.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res3.1.conv1.weight
  backbone.res3.1.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res3.1.conv2.weight
  backbone.res3.1.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res3.1.conv3.weight
  backbone.res3.1.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res3.2.conv1.weight
  backbone.res3.2.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res3.2.conv2.weight
  backbone.res3.2.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res3.2.conv3.weight
  backbone.res3.2.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res3.3.conv1.weight
  backbone.res3.3.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res3.3.conv2.weight
  backbone.res3.3.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res3.3.conv3.weight
  backbone.res3.3.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res4.0.shortcut.weight
  backbone.res4.0.shortcut.norm.{bias, running_mean, running_var, weight}
  backbone.res4.0.conv1.weight
  backbone.res4.0.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res4.0.conv2.weight
  backbone.res4.0.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res4.0.conv3.weight
  backbone.res4.0.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res4.1.conv1.weight
  backbone.res4.1.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res4.1.conv2.weight
  backbone.res4.1.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res4.1.conv3.weight
  backbone.res4.1.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res4.2.conv1.weight
  backbone.res4.2.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res4.2.conv2.weight
  backbone.res4.2.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res4.2.conv3.weight
  backbone.res4.2.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res4.3.conv1.weight
  backbone.res4.3.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res4.3.conv2.weight
  backbone.res4.3.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res4.3.conv3.weight
  backbone.res4.3.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res4.4.conv1.weight
  backbone.res4.4.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res4.4.conv2.weight
  backbone.res4.4.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res4.4.conv3.weight
  backbone.res4.4.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res4.5.conv1.weight
  backbone.res4.5.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res4.5.conv2.weight
  backbone.res4.5.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res4.5.conv3.weight
  backbone.res4.5.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res5.0.shortcut.weight
  backbone.res5.0.shortcut.norm.{bias, running_mean, running_var, weight}
  backbone.res5.0.conv1.weight
  backbone.res5.0.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res5.0.conv2.weight
  backbone.res5.0.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res5.0.conv3.weight
  backbone.res5.0.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res5.1.conv1.weight
  backbone.res5.1.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res5.1.conv2.weight
  backbone.res5.1.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res5.1.conv3.weight
  backbone.res5.1.conv3.norm.{bias, running_mean, running_var, weight}
  backbone.res5.2.conv1.weight
  backbone.res5.2.conv1.norm.{bias, running_mean, running_var, weight}
  backbone.res5.2.conv2.weight
  backbone.res5.2.conv2.norm.{bias, running_mean, running_var, weight}
  backbone.res5.2.conv3.weight
  backbone.res5.2.conv3.norm.{bias, running_mean, running_var, weight}
640 640 600
confidence thresh:  0.21
image after transform:  (398, 600, 3)
cost: 0.0565032958984375, fps: 17.698082635700782
Traceback (most recent call last):
  File "demo.py", line 211, in <module>
    res = vis_res_fast(res, img, class_names, colors, conf_thresh)
  File "demo.py", line 153, in vis_res_fast
    img = vis_bitmasks_with_classes(
  File "/XXX/python3.8/site-packages/alfred/vis/image/mask.py", line 272, in vis_bitmasks_with_classes
    cts, _ = cv2.findContours(m, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack (expected 2)
`

vis_bitmasks_with_classes function has a bug？ Or I do error?

**Comment by jinfagang** [comment]
Please upgrade opencv-python to latest.
