### ISSUE TITLE
need help with training custom datase

### ISSUE THREAD

**Issue by totoadel** [jinfagang/yolov7#65]
i want to train custom dataset to train instance with detectron2,
my problem is the traing command , which training .py file i should use 
i need the training line ,just that.

**Comment by jinfagang** [comment]
using `train_customdatasets.py` it was very clear.

**Comment by totoadel** [comment]
i done it with this 
`!python train_custom_datasets.py --config-file /content/yolov7/configs/coco/sparseinst/Base-SparseInst.yaml --num-gpus 1`

but 
i got this error 
`[07/01 11:02:24 d2.data.common]: Serialized dataset takes 19.10 MiB
[07/01 11:02:25 d2.evaluation.evaluator]: Start inference on 5000 batches
Traceback (most recent call last):
  File "train_custom_datasets.py", line 156, in <module>
    args=(args,),
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_custom_datasets.py", line 144, in main
    return trainer.train()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/defaults.py", line 484, in train
    super().train(self.start_iter, self.max_iter)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/train_loop.py", line 159, in train
    self.after_train()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/train_loop.py", line 168, in after_train
    h.after_train()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/hooks.py", line 560, in after_train
    self._do_eval()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/hooks.py", line 528, in _do_eval
    results = self._func()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/defaults.py", line 453, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/engine/defaults.py", line 617, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/evaluation/evaluator.py", line 164, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/evaluation/coco_evaluation.py", line 171, in process
    prediction["instances"] = instances_to_coco_json(instances, input["image_id"])
  File "/usr/local/lib/python3.7/dist-packages/detectron2/evaluation/coco_evaluation.py", line 407, in instances_to_coco_json
    boxes = instances.pred_boxes.tensor.numpy()
  File "/usr/local/lib/python3.7/dist-packages/detectron2/structures/instances.py", line 65, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'pred_boxes' in the given Instances!`

**Comment by totoadel** [comment]
@jinfagang 
what about` train_cocomini.py`  is doing the same  job 
and about `train_coco` , where to add the datasets reference 
like that 
```

    DATASET_ROOT = "./datasets/coco"
    ANN_ROOT = os.path.join(DATASET_ROOT, "annotations")
    TRAIN_PATH = os.path.join(DATASET_ROOT, "cocotrain2017")
    VAL_PATH = os.path.join(DATASET_ROOT, "cocotval2017")
    TRAIN_JSON = os.path.join(ANN_ROOT, "train.json")
    VAL_JSON = os.path.join(ANN_ROOT, "val.json")
    register_coco_instances("mask_train", {}, TRAIN_JSON, TRAIN_PATH)
    register_coco_instances("mask_val", {}, VAL_JSON, VAL_PATH)

```
