### ISSUE TITLE
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by totoadel** [jinfagang/yolov7#67]
i run demo
`!python3 demo.py --config-file /content/yolov7/configs/coco/darknet53.yaml --input /content/yolov7/datasets/coco/test2017/ --opts MODEL.WEIGHTS /content/yolov7/output/model_final.pth`

and got this error

```
800 800 600
confidence thresh:  0.21
image after transform:  (450, 600, 3)
cost: 0.07432031631469727, fps: 13.455271042788125
Traceback (most recent call last):
  File "demo.py", line 201, in <module>
    res = vis_res_fast(res, im, class_names, colors, conf_thresh)
  File "demo.py", line 158, in vis_res_fast
    if bboxes:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by jinfagang** [comment]
Please send me a PR to fix it.

**Comment by totoadel** [comment]
@jinfagang what do you means by PR
