### ISSUE TITLE
Coco keypoints detection training

### ISSUE THREAD

**Issue by maketo97** [jinfagang/yolov7#78]
> Traceback (most recent call last):
  File "train_net.py", line 111, in <module>
    launch(
  File "d:\detectron2\detectron2\engine\launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 100, in main
    trainer = Trainer(cfg)
  File "d:\detectron2\detectron2\engine\defaults.py", line 378, in __init__
    data_loader = self.build_train_loader(cfg)
  File "train_net.py", line 44, in build_train_loader
    return build_detection_train_loader(cfg, mapper=cls.custom_mapper)
  File "d:\detectron2\detectron2\config\config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "d:\detectron2\detectron2\config\config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "d:\detectron2\detectron2\data\build.py", line 344, in _train_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "d:\detectron2\detectron2\data\build.py", line 278, in get_detection_dataset_dicts
    assert len(dataset_dicts), "No valid data found in {}.".format(",".join(names))
AssertionError: No valid data found in coco_2017_train.

@jinfagang May I know how to solve this error?

**Comment by jinfagang** [comment]
I don't know, I am gonna delete this repo soon.

**Comment by maketo97** [comment]
Gonna move to new repo?

**Comment by jinfagang** [comment]
No, as for the official YOLOv7 released, I all make a place for them....
