### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/content/yolov7/configs/Base-YoloV7.yaml'

### ISSUE THREAD

**Issue by totoadel** [jinfagang/yolov7#86]
i run custom traning on colab
i run this command 
```
%cd /content/yolov7
!python  train_ahmed.py --config-file 'configs/balloon/darknet53.yaml' --num-gpus 1
```

and got this error 

```
`/content/yolov7
Install mish-cuda to speed up training and inference. More importantly, replace the naive Mish with MishCuda will give a ~1.5G memory saving during training.
Traceback (most recent call last):
  File "train_ahmed.py", line 61, in <module>
    args=(args,),
  File "/content/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_ahmed.py", line 39, in main
    cfg = setup(args)
  File "/content/yolov7/train_det.py", line 62, in setup
    cfg.merge_from_file(args.config_file)
  File "/content/detectron2/detectron2/config/config.py", line 46, in merge_from_file
    loaded_cfg = self.load_yaml_with_base(cfg_filename, allow_unsafe=allow_unsafe)
  File "/usr/local/lib/python3.7/dist-packages/fvcore/common/config.py", line 103, in load_yaml_with_base
    base_cfg = _load_with_base(base_cfg_file)
  File "/usr/local/lib/python3.7/dist-packages/fvcore/common/config.py", line 93, in _load_with_base
    return cls.load_yaml_with_base(base_cfg_file, allow_unsafe=allow_unsafe)
  File "/usr/local/lib/python3.7/dist-packages/fvcore/common/config.py", line 59, in load_yaml_with_base
    with cls._open_cfg(filename) as f:
  File "/content/detectron2/detectron2/config/config.py", line 34, in _open_cfg
    return PathManager.open(filename, "r")
  File "/usr/local/lib/python3.7/dist-packages/iopath/common/file_io.py", line 1012, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/iopath/common/file_io.py", line 612, in _open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: 'configs/Base-YoloV7.yaml'`
```

**Comment by jieruyao49** [comment]
I meet same question. Have you solved it?
